### PR TITLE
v1.9.8 manual (shared on all platforms)

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
If this works out and builds shared libs, I think we will need to create a repodata patch on Windows. As far as I understand so far static libs were built on Windows, whereas with this new patch, shared libs would be built. So far, there have been no run_exports on Windows.

Do you have any thoughts @traversaro @wolfv @jcarpent?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Note that this would also remove the static libs on the other platforms. I think this is generally the right approach for conda-forge, but not sure how much this is going to break downstream packages.

**Comment by Tobias-Fischer** [comment]
Downstream packages:
- dartsim
- fcl
- gepetto-viewer
- hpp-fcl
- hpp-gepetto-viewer
- hpp-manipulation
- hpp-manipulation-corba
- hpp-manipulation-urdf
- hpp-pinocchio

**Comment by Tobias-Fischer** [comment]
So in principle, this seems ready to go. Is there a way to create a repodata patch that sets the max_pin of all previous builds to 1.9.7 (on all platforms)? Then all previous builds should be unaffected by the new build, and starting with 1.9.8, we can go with `max_pin(x.x)'.

**Comment by traversaro** [comment]
> Note that this would also remove the static libs on the other platforms. I think this is generally the right approach for conda-forge, but not sure how much this is going to break downstream packages.

Based on https://github.com/conda-forge/cfep/blob/main/cfep-18.md, this is indeed the correct way to go.

> If this works out and builds shared libs, I think we will need to create a repodata patch on Windows. As far as I understand so far static libs were built on Windows, whereas with this new patch, shared libs would be built. So far, there have been no run_exports on Windows.
> 
> Do you have any thoughts @traversaro @wolfv @jcarpent?

If previous build were using static libraries, then they do not need octomap at runtime, and so I do not think we need to do a repodata patch, unless I am missing something.

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro! In this case even better. @jcarpent @wolfv  this is ready to be merged.

**Comment by Tobias-Fischer** [comment]
Kind reminder @wolfv

**Pull request merged**
