### PR TITLE
v1.9.8 manual - static on win, shared+static on others

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This PR is an alternative to #14 where Windows builds only build static libs, and Linux/OSX continue to build shared+static libs

**Comment by Tobias-Fischer** [comment]
Caveat here is that the static libs on windows now have a different name - not sure if that is important?
@traversaro @jcarpent @wolfv

**Comment by Tobias-Fischer** [comment]
We could probably create an alias in cmake to make sure the lib names remain the same?

**Comment by Tobias-Fischer** [comment]
Actually the lib names are the same already - so this PR should be ready to go without needing any repo data patches

**Comment by traversaro** [comment]
> This PR is an alternative to #14 where Windows builds only build static libs, and Linux/OSX continue to build shared+static libs

Given https://github.com/conda-forge/cfep/blob/main/cfep-18.md, I would personally prefer to go on with #14 .

**Pull request closed without merging**
