### PR TITLE
Update to v1.10.0

### PR DESCRIPTION
**Pull request by jeongseok-meta**
Resolves #17 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
Added patch for https://github.com/OctoMap/octomap/pull/417

**Comment by jeongseok-meta** [comment]
@jcarpent @wolfv Could someone please review this PR? Thanks!

**Comment by jeongseok-meta** [comment]
The older version (1.9.8) cannot build with C++20 without https://github.com/OctoMap/octomap/pull/398. The fix is included in version 1.10.0.

**Comment by wolfv** [comment]
Hi @jeongseok-meta thank you for volunteering to be a co-maintainer! :) Sorry for being slow. This looks great!

**Comment by jeongseok-meta** [comment]
@wolfv Yeah, I'm happy to help! Thank you for accepting me as a co-maintainer.

**Pull request merged**
